### ISSUE TITLE
Map shows incorrect location of Polkadot Node 

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/dotstats#17]
With reference to #7, since I'm in the Berlin office I'm running a Polkadot Node that has uses Berlin slang in its name, but when I toggle the map it says it's located at Frankfurt am Main.

![screen shot 2018-07-24 at 3 30 00 pm](https://user-images.githubusercontent.com/6226175/43141602-9c2e7de2-8f56-11e8-9294-6b27024402af.png)

**Comment by maciejhirsz** [comment]
That's just iplocation being what it is, I'm using https://www.npmjs.com/package/iplocation on the server. Will gladly accept suggestions for something more precise :).

**Comment by ltfschoen** [comment]
I had a look around this morning. I'll try using the following packages and compare the results:

https://www.npmjs.com/package/geolocator
https://www.npmjs.com/package/react-geolocated
https://www.npmjs.com/package/ipdata
https://github.com/bluesmoon/node-geoip
https://dev.maxmind.com/geoip/geoip2/web-services/
https://ipinfo.io/developers
https://github.com/IonicaBizau/node-ipinfo

https://stackoverflow.com/questions/7541779/why-html5-geolocation
https://stackoverflow.com/questions/16664623/best-node-js-module-for-finding-location

**Comment by maciejhirsz** [comment]
Now that he server is stable, it seems there is an issue with existing node locations:

1) We should cache the result for iplocation at very least, otherwise nodes reconnecting quickly exhaust the free tier for iplocation.
2) If a location for a node isn't found when it first connects, have retry function (might be a long time, few hours)? It's okay if we can't geolocate all nodes, but right now the map looks pretty sad :).

**Comment by maciejhirsz** [comment]
Fixed!
